$schema: https://azuremlschemas.azureedge.net/latest/modelBatchDeployment.schema.json
type: model
model: azureml:diabetes-gs-model@latest
compute: azureml:cpu-cluster
resources:
  instance_count: 2
settings:
  max_concurrency_per_instance: 2
  mini_batch_size: 2
  output_action: append_row
  output_file_name: predictions.csv
  retry_settings:
    max_retries: 3
    timeout: 300
  error_threshold: -1
  logging_level: info
