name: Manually trigger an Azure Machine Learning job
# Controls when the workflow will run 
on:
  workflow_dispatch:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit ML job
      run: az ml job create --file src/job.yml --resource-group rg-tccc-ms-training-for-dts-dsml-poc --workspace-name aml-tccc-ms-training-dts-dsml-poc --stream
  production:
    runs-on: ubuntu-latest
    needs: [experiment]
    environment:
      name: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit ML job
      run: az ml job create --file src/job-prod.yml --resource-group rg-tccc-ms-training-for-dts-dsml-poc --workspace-name aml-tccc-ms-training-dts-dsml-poc --stream  
